### ISSUE TITLE
Prise en charge des calculs sans résultat

### ISSUE THREAD

**Issue by alhyss** [MTES-MCT/metadata-postgresql#176]
Lorsque la fonctionnalité de calcul de métadonnées côté serveur ne renvoie pas de résultat, la retranscription dans les fiches de métadonnées présente des anomalies.

Tests réalisés avec un modèle pour lequel le calcul était activé sur les métadonnées *Libellé* / `dct:title`, *Thèmes* / `dcat:theme` et *Conforme à* / `dct:conformsTo`.

```sql
INSERT INTO z_plume.meta_template (tpl_id, tpl_label) VALUES 
    (100, 'Test modèle 2') ;
INSERT INTO z_plume.meta_template_categories (tpl_id, shrcat_path, compute, template_order) VALUES
    (100, 'dct:conformsTo', ARRAY['auto'], 3),
    (100, 'dcat:theme', ARRAY['auto', 'manual'], 2),
    (100, 'dct:title', ARRAY['auto'], 1) ;
```

En mode lecture, l'utilisateur voit des champs et groupes vides.

![image](https://github.com/MTES-MCT/metadata-postgresql/assets/55992003/3a3fee06-c332-4254-b8cc-ef302e19e19e)

Ce n'est pas satisfaisant, mais ça ne prête pas vraiment à conséquence.

En mode écriture, il voit des groupes vides avec des boutons plus.

![image](https://github.com/MTES-MCT/metadata-postgresql/assets/55992003/af271fcc-3d61-480b-9594-c2bee4d9832a)

Comme il n'y a pas de champ, ça empêche la saisie manuelle. Et cliquer sur le bouton plus fait planter QGIS, car il n'y a pas de clé à recopier dans le groupe...

```python
Traceback (most recent call last):
  File "C:\Users/alhyss/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\plume\bibli_gene_objets.py", line 513, in 
    _mObjetQToolButton.clicked.connect(lambda : action_mObjetQToolButton_Plus_translation(self, _keyObjet, _valueObjet, _language, _langList))
  File "C:\Users/alhyss/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\plume\bibli_gene_objets.py", line 1070, in action_mObjetQToolButton_Plus_translation
    ret = self.mDicObjetsInstancies.add(__keyObjet)
  File "C:\Users/alhyss/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\plume\rdf\widgetsdict.py", line 952, in add
    a = buttonkey.add()
  File "C:\Users/alhyss/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\plume\rdf\widgetkey.py", line 5165, in add
    raise IntegrityBreach(
plume.rdf.exceptions.IntegrityBreach: Le groupe ne contient aucune clé duplicable. PlusButtonKey "dcat:theme" 9a83f6b5-a7ce-45fc-8af4-a30c340158b8.
```

**Comment by alhyss** [comment]
Après correction.

En mode lecture, Plume ne montre plus ni de champ vide, ni de groupe vide, ni d'onglet vide, ce qui - dans ce exemple, provoque donc la disparition complète de l'onglet *Général*.

![image](https://github.com/MTES-MCT/metadata-postgresql/assets/55992003/5182e629-fd2a-43ad-882f-2bdf66dc4dda)

Le résultat est équivalent à ce voit l'utilisateur dans le cas d'une table sans métadonnées.

À titre de comparaison, toujours en mode lecture, mais sur une fiche pour laquelle le calcul des métadonnées *Thèmes* et *Conforme à* renvoie un résultat : 

![image](https://github.com/MTES-MCT/metadata-postgresql/assets/55992003/d30d8de8-4cb8-4cef-9121-e41c5323989d)

Les mêmes fiches en mode écriture + traduction : 

![image](https://github.com/MTES-MCT/metadata-postgresql/assets/55992003/0e77ec80-4d11-46fa-899b-01c2ceae42bc)

![image](https://github.com/MTES-MCT/metadata-postgresql/assets/55992003/6dbcd686-9d6b-4bfe-8c36-42f0cf957867)
